Repository Teammanagers/Frontend-V2, pull requests merged in 2025-03, with the labels that each got.

#13 [TM-121] 투두 이미지 업로드 모달 UI 구현
  .env
  index.html
  public/favicon.svg
  public/vite.svg
  src/app/providers/TodoContext.tsx
  src/app/styles/index.css
  src/entities/todo/constants/status-label.ts
  src/entities/todo/mocks/get-todo-list.json
  src/entities/todo/model/useTodoContext.ts
  src/entities/todo/todo.type.ts
  src/entities/todo/ui/ActionDropdown.tsx
  src/entities/todo/ui/ImageUploadModal.tsx
  src/entities/todo/ui/Todo.tsx
  src/entities/todo/ui/TodoStatus.tsx
  src/entities/todo/ui/index.ts
  src/pages/test/modal.tsx
  src/shared/assets/icons/image-upload.svg
  src/shared/components/accordion/Accordion.tsx
  src/shared/components/accordion/Body.tsx
  src/shared/components/accordion/Header.tsx
  src/shared/components/accordion/index.ts
  src/shared/components/dropdown/compound/Dropdown.tsx
  src/shared/components/dropdown/hooks/useToggle.ts
  src/shared/components/dropdown/index.ts
  src/shared/components/modal/Modal.tsx
  src/shared/hooks/action/useAccordionToggle.ts
  src/shared/hooks/action/useClickOutstide.ts
  src/shared/hooks/action/useToggle.ts
  src/shared/hooks/index.ts
  src/shared/types/accordion.types.ts
  src/shared/types/context/todo-context.types.ts
  src/shared/types/index.ts
  src/widgets/todo/TeamProgres.tsx
  src/widgets/todo/TodoList.tsx
Labels: ✨ Feature

#12 [TM-120] API 기본 세팅
  .gitignore
  src/shared/api/apiRequest.ts
  src/shared/api/axiosInstance.ts
  src/shared/components/modal/Modal.tsx
  src/shared/types/api.types.ts
Labels: ✨ Feature

#15 [TM-34] 메인 UI 구현
  src/app/providers/TodoContext.tsx
  src/app/routes/routes.tsx
  src/app/styles/index.css
  src/entities/main/main.types.ts
  src/entities/main/ui/RoutingButton.tsx
  src/entities/main/ui/index.ts
  src/entities/notice/ui/NoticeBanner.tsx
  src/entities/notice/ui/NoticeInput.tsx
  src/entities/notice/ui/NoticeItem.tsx
  src/entities/notice/ui/TeamCodeCopy.tsx
  src/entities/notice/ui/index.ts
  src/entities/schedule/ui/UpcomingSchedule.tsx
  src/entities/schedule/ui/index.ts
  src/entities/todo/ui/ActionDropdown.tsx
  src/entities/todo/ui/Todo.tsx
  src/pages/MainPage/main.tsx
  src/pages/test/modal.tsx
  src/shared/assets/icons/main/loud-speaker.svg
  src/shared/assets/icons/main/notice-submit-btn.svg
  src/shared/components/accordion/Accordion.tsx
  src/shared/components/dropdown/compound/Dropdown.tsx
  src/shared/components/modal/Modal.tsx
  src/shared/components/routing-button/RoutingButton.tsx
  src/shared/hooks/action/useAccordionToggle.ts
  src/shared/hooks/action/useBulletPointConverter.ts
  src/shared/hooks/action/useClickOutstide.ts
  src/shared/hooks/action/useToggle.ts
  src/shared/hooks/index.ts
  src/shared/lib/utils/handleNoticeInputChange.ts
  src/shared/types/accordion.types.ts
  src/shared/types/components.types.ts
  src/shared/types/context.types.ts
  src/shared/types/hooks.types.ts
  src/shared/types/index.ts
  src/shared/types/modal.types.ts
  src/shared/types/utils.types.ts
  src/widgets/main/TodoList.tsx
  src/widgets/main/UpcomingScheduleList.tsx
  src/widgets/main/index.ts
  src/widgets/notice/NoticeModal.tsx
  src/widgets/notice/notice-modal.types.ts
  src/widgets/todo/TodoList.tsx
Labels: ✨ Feature

#14 [TM-122] 스켈레톤, ActionDropdown 공통 컴포넌트 구현
  src/app/routes/routes.tsx
  src/entities/todo/ui/Todo.tsx
  src/entities/todo/ui/index.ts
  src/pages/test/modal.tsx
  src/shared/components/dropdown/ActionDropdown.tsx
  src/shared/components/dropdown/index.ts
  src/shared/components/dropdown/plate/Dropdown.tsx
  src/shared/components/dropdown/plate/Menu.tsx
  src/shared/components/dropdown/plate/Trigger.tsx
  src/shared/components/skeleton/Skeleton.tsx
  src/shared/types/components/dropdown.types.ts
  src/shared/types/components/index.ts
  src/shared/types/components/skeleton.types.ts
  src/shared/types/modal.types.ts
Labels: ✨ Feature, 🔨 Refactor

#20 [TM-125] SVGR 환경 세팅 수정
  .gitignore
  src/entities/main/ui/RoutingButton.tsx
  src/entities/notice/ui/NoticeBanner.tsx
  src/entities/notice/ui/NoticeInput.tsx
  src/entities/todo/constants/todo.ts
  src/entities/todo/todo.type.ts
  src/entities/todo/ui/ActionDropdown.tsx
  src/entities/todo/ui/ImageUploadModal.tsx
  src/entities/todo/ui/ProgressBar.tsx
  src/entities/todo/ui/ProgressStatusBadge.tsx
  src/entities/todo/ui/TodoStatus.tsx
  src/entities/todo/ui/index.ts
  src/shared/assets/common/arrow.svg
  src/shared/assets/common/routing-arrow.svg
  src/shared/assets/icons/dropdown.svg
  src/shared/assets/main/loud-speaker.svg
  src/shared/assets/main/notice-submit-btn.svg
  src/shared/assets/todo/check.svg
  src/shared/assets/todo/image-upload.svg
  src/shared/components/dropdown/ActionDropdown.tsx
  src/shared/components/dropdown/plate/Dropdown.tsx
  src/shared/components/dropdown/plate/Menu.tsx
  src/shared/components/dropdown/plate/Trigger.tsx
  src/shared/components/skeleton/Skeleton.tsx
  src/shared/types/components.types.ts
  src/shared/types/components/dropdown.types.ts
  src/shared/types/components/index.ts
  src/shared/types/components/skeleton.types.ts
  src/vite-env.d.ts
  src/widgets/main/TodoList.tsx
  src/widgets/todo/TeamProgres.tsx
  src/widgets/todo/status.type.ts
  tsconfig.json
  vite.config.ts
Labels: 🐞 BugFix, 🔧 Configuration

#21 [TM-113] 캘린더 다가오는 일정 / 일정 등록 모달 UI 구현
  src/app/styles/index.css
  src/entities/todo/todo.type.ts
  src/entities/todo/ui/index.ts
  src/pages/CalendarPage/calendar.tsx
  src/shared/assets/common/delete.svg
  src/shared/assets/common/plus.svg
  src/shared/types/modal.types.ts
  src/widgets/calendar/EventCalendar.tsx
  src/widgets/calendar/EventEditorModal.tsx
  src/widgets/calendar/EventSummaryPopover.tsx
  src/widgets/calendar/calendar.types.ts
  src/widgets/main/TodoList.tsx
  src/widgets/todo/ImageUploadModal.tsx
  src/widgets/todo/TodoList.tsx
  src/widgets/todo/todo.types.ts
Labels: ✨ Feature

#22 메모 컴포넌트 UI
  src/entities/memo/assets/add-memo.svg
  src/entities/memo/assets/plus.svg
  src/entities/memo/memo.type.ts
  src/entities/memo/ui/AddButton.tsx
  src/entities/memo/ui/AddMemo.tsx
  src/entities/memo/ui/AddModal.tsx
  src/entities/memo/ui/DeleteModal.tsx
  src/entities/memo/ui/Folder.tsx
  src/entities/memo/ui/FolderModal.tsx
  src/entities/memo/ui/MemoForm.tsx
  src/entities/memo/ui/MoveModal.tsx
  src/shared/assets/common/add-tag.svg
  src/shared/assets/memo/add-folder.svg
  src/shared/assets/memo/add-memo.svg
  src/shared/assets/memo/back-button.svg
  src/shared/assets/memo/folder.svg
  src/shared/assets/memo/next-button.svg
  src/shared/assets/memo/pin.svg
  src/widgets/memo/Memo.tsx
  src/widgets/memo/memo.constants.ts
Labels: ✨ Feature
