Repository Teammanagers/Frontend-V2, pull requests merged in 2025-05, with the labels that each got.

#29 Modal on off
  src/entities/memo/ui/AddModal.tsx
  src/entities/memo/ui/DeleteModal.tsx
  src/entities/memo/ui/FolderModal.tsx
  src/entities/memo/ui/MoveModal.tsx
  src/shared/types/modal.types.ts
  src/widgets/memo/MemoList.tsx
Labels: 🔨 Refactor

#30 [TM-132] 캘린더 일정 CURD 구현
  .env
  src/entities/calendar/calendar.types.ts
  src/entities/calendar/config/calendar.constants.ts
  src/entities/calendar/model/useEventQueries.ts
  src/entities/calendar/ui/ActionButton.tsx
  src/entities/calendar/ui/EventSummary.tsx
  src/entities/calendar/ui/UpcomingSchedule.tsx
  src/entities/calendar/ui/index.ts
  src/entities/notice/ui/NoticeInputForm.tsx
  src/entities/notice/ui/NoticeList.tsx
  src/entities/schedule/ui/index.ts
  src/pages/CalendarPage/calendar.tsx
  src/pages/MainPage/main.tsx
  src/shared/api/axiosInstance.ts
  src/shared/config/constants/team.constants.ts
  src/shared/hooks/useDelayPendingState.ts
  src/shared/lib/utils/handleNoticeInputChange.ts
  src/shared/lib/utils/inputChangeHandler.ts
  src/shared/types/utils.types.ts
  src/widgets/calendar/calendar.types.ts
  src/widgets/calendar/mocks/getSimpleCalendarList.json
  src/widgets/calendar/ui/EventCalendar.tsx
  src/widgets/calendar/ui/EventEditorModal.tsx
  src/widgets/calendar/ui/EventSummaryPopover.tsx
  src/widgets/main/UpcomingScheduleList.tsx
  src/widgets/main/index.ts
  src/widgets/upcoming-event/UpcomingEventList.tsx
  src/widgets/upcoming-event/index.ts
Labels: ✨ Feature

#31 [TM-134] 일정 완료 관련 로직 제거
  src/entities/calendar/calendar.types.ts
  src/entities/calendar/model/useEventQueries.ts
  src/entities/calendar/ui/EventSummary.tsx
  src/widgets/calendar/ui/EventEditorModal.tsx
  src/widgets/calendar/ui/EventSummaryPopover.tsx
Labels: ✨ Feature

#32 [TM-131] MVVM 패턴을 활용하여 캘린더 로직 및 구조 리팩토링
  src/entities/calendar/calendar.constants.ts
  src/entities/calendar/calendar.types.ts
  src/entities/calendar/ui/ActionButton.tsx
  src/entities/calendar/ui/EventSummary.tsx
  src/entities/calendar/ui/UpcomingSchedule.tsx
  src/features/calendar/calendar.constants.ts
  src/features/calendar/calendar.types.ts
  src/features/calendar/lib/calculatePopoverPosition.ts
  src/features/calendar/lib/index.ts
  src/features/calendar/lib/usePopoverAnimation.ts
  src/features/calendar/lib/usePopoverRender.tsx
  src/features/calendar/model/calendarStore.ts
  src/features/calendar/model/index.ts
  src/features/calendar/model/useEditorModalViewModel.ts
  src/features/calendar/model/useEventQueries.ts
  src/features/calendar/model/usePopoverViewModel.ts
  src/features/calendar/ui/EventEditorModal.tsx
  src/features/calendar/ui/EventSummaryPopover.tsx
  src/features/calendar/ui/index.ts
  src/pages/CalendarPage/calendar.tsx
  src/shared/hooks/action/useClickOutside.ts
  src/widgets/calendar/calendar.constants.ts
  src/widgets/calendar/calendar.types.ts
  src/widgets/calendar/config/calendar.constants.ts
  src/widgets/calendar/lib/getCalendarHeight.ts
  src/widgets/calendar/model/useCalendarViewModel.ts
  src/widgets/calendar/ui/EventCalendar.tsx
  src/widgets/upcoming-event/UpcomingEventList.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 🔨 Refactor

#33 Management UI
  src/app/routes/routes.tsx
  src/entities/management/dummySchedule.ts
  src/entities/management/lib/timeSlots.ts
  src/entities/management/management.types.ts
  src/entities/management/model/ScheduleDto.ts
  src/entities/management/ui/Member.tsx
  src/entities/management/ui/NoSchedule.tsx
  src/entities/management/ui/Schedule.tsx
  src/entities/management/ui/ShowSchedule.tsx
  src/entities/management/ui/TeamInfo.tsx
  src/entities/management/ui/TeamMember.tsx
  src/entities/management/ui/TimeSelector.tsx
  src/pages/Management Page/management.tsx
  src/pages/ManagementPage/index.ts
  src/pages/ManagementPage/management.tsx
  src/shared/assets/common/arrow.svg
  src/shared/assets/common/delete-tag.svg
  src/shared/assets/common/plus.svg
  src/shared/assets/management/edit.svg
  src/shared/assets/management/profile-img-default.svg
  src/shared/assets/management/upload-icon.svg
Labels: 🚧 Draft

#34 [TM-133] Pending 렌더링 버그 수정, 개행 및 말줄임표 UI 대응
  src/entities/calendar/ui/EventSummary.tsx
  src/entities/main/ui/RoutingButton.tsx
  src/entities/notice/ui/NoticeInputForm.tsx
  src/entities/notice/ui/NoticeItem.tsx
  src/entities/notice/ui/NoticeList.tsx
  src/features/calendar/ui/EventEditorModal.tsx
  src/features/calendar/ui/EventSummaryPopover.tsx
  src/shared/hooks/useDelayPendingState.ts
  src/widgets/notice/NoticeBanner.tsx
  src/widgets/upcoming-event/UpcomingEventList.tsx
Labels: 🐞 BugFix
